backend:
  name: git-gateway
  branch: main

media_folder: static/media
public_folder: /media

collections:
  - name: "stories"
    label: "Stories"
    folder: "stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Audio", name: "audio", widget: "file", media_library: { allow_multiple: false }, required: true }
      - { label: "Body", name: "body", widget: "text" }
